# Generated by Django 5.1.1 on 2024-10-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField()),
                ('shift_date', models.DateField()),
                ('shift_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
