# Generated by Django 5.1.1 on 2024-10-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSchedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emschedule',
            options={'ordering': ['employee_id']},
        ),
    ]
