# Generated by Django 5.1.2 on 2024-11-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_options_order_total_items_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
