# Generated by Django 5.1.2 on 2024-12-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_name', models.CharField(max_length=100)),
                ('reservation_date', models.DateField()),
                ('number_of_people', models.IntegerField()),
            ],
        ),
    ]
