# Generated by Django 5.1.2 on 2024-12-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='Reservation_reservation',
        ),
    ]
