# Generated by Django 5.1.2 on 2024-11-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier_home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
