# Generated by Django 5.1.2 on 2024-11-30 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier_home', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(default=models.F('order__order_date'))),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cashier_home.order')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
