# Generated by Django 5.1.2 on 2024-11-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeSchedule', '0002_alter_emschedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emschedule',
            name='employee_role',
            field=models.CharField(choices=[('executive_chef', 'Executive Chef'), ('kitchen_manager', 'Kitchen Manager'), ('sous_chef', 'Sous Chef'), ('station_chef', 'Station Chef'), ('cook', 'Cook'), ('assistant_cook', 'Assistant Cook'), ('cleaning_team', 'Cleaning Team'), ('head_waiter', 'Head Waiter'), ('receptionist', 'Receptionist'), ('sommelier', 'Sommelier'), ('bar_staff', 'Bar Staff'), ('waiter', 'Waiter')], default='waiter', max_length=50),
        ),
    ]
