# Generated by Django 5.1.2 on 2024-12-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_payment_payment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
